version: "3.6"
services:
    sqlserver:
      image: mcr.microsoft.com/mssql/server:2017-latest
      environment:
        - SA_PASSWORD=@Sqlserver
        - ACCEPT_EULA=Y
      ports:
        - "1433:1433"
